version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: safe_hire_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: safe_hire_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=safe_hire_db
      - JWT_SECRET=safe_hire_production_jwt_secret_key_2026
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: safe_hire_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
