import logging
from typing import List, Dict, Any

logger = logging.getLogger("safe_hire.recommendation_agent")

class RecommendationAgent:
    """Agent 5: Generates dynamic, context-aware safety recommendations tied to actual detected evidence."""

    def generate_recommendations(
        self,
        scam_score: Any,
        risk_factors: dict,
        verification_data: dict,
        language: str = "en",
        reasoning_data: dict = None,
        intake_data: dict = None
    ) -> List[str]:
        reasoning_data = reasoning_data or {}
        intake_data = intake_data or {}
        risk_factors = risk_factors or {}
        verification_data = verification_data or {}

        # 1. Use high-quality AI recommendations if generated by Reasoning Agent
        ai_recs = reasoning_data.get("recommendations", [])
        if isinstance(ai_recs, list) and len(ai_recs) >= 2:
            return [str(r).strip() for r in ai_recs if str(r).strip()]

        dynamic_recs: List[str] = []

        # 2. Non-Job Content Recommendation
        if intake_data.get("is_job_poster") is False or reasoning_data.get("risk_level") == "Not a Job Advertisement":
            specific_category = intake_data.get("specific_category", "Non-Recruitment Media")
            return [
                f"Please upload a genuine recruitment flyer or job vacancy URL to receive a recruitment scam risk audit (current upload identified as {specific_category}).",
                "Verify any educational events, commercial promotions, or services directly through the official organizers' website."
            ]

        # 3. Exact Fee Terms & Financial Payment Demand Warning
        matched_payment = risk_factors.get("matched_payment")
        if risk_factors.get("has_payment_demand") or matched_payment:
            fee_term = ", ".join(matched_payment) if isinstance(matched_payment, list) else (str(matched_payment) if matched_payment else "upfront fee")
            dynamic_recs.append(
                f"🚨 UPFRONT PAYMENT WARNING: Never transfer money for '{fee_term}'. Legitimate employers never charge candidates for recruitment, laptop processing, or training."
            )

        # 4. Brand Impersonation & Recruiter Email Signal
        claimed_brand = risk_factors.get("claimed_brand") or intake_data.get("claimed_brand")
        free_email = risk_factors.get("free_email")
        email_val = verification_data.get("email_validation") or {}
        contact_email = email_val.get("email") or (intake_data.get("metadata_extracted") or {}).get("emails", [""])[0]

        if claimed_brand:
            if free_email or risk_factors.get("has_impersonation_risk"):
                dynamic_recs.append(
                    f"⚠️ BRAND VERIFICATION ({claimed_brand.upper()}): This posting claims to represent '{claimed_brand}' but uses an informal email address ({contact_email or '@' + free_email}). Cross-check the vacancy directly on the official career portal of {claimed_brand}."
                )
            else:
                dynamic_recs.append(
                    f"🏢 CAREER PORTAL VERIFICATION: Look up this vacancy directly on the official website or LinkedIn page of '{claimed_brand}' before sharing personal documents."
                )
        elif contact_email:
            dynamic_recs.append(
                f"📧 RECRUITER VERIFICATION: Check the sender address '{contact_email}' against the company's verified email domain before sending CV or identity details."
            )

        # 5. Domain & Web Threat Warnings
        domain = verification_data.get("domain")
        whois_info = verification_data.get("whois_info") or {}
        safe_browsing = verification_data.get("safe_browsing") or {}

        if domain and domain != "Not Specified":
            if safe_browsing.get("flagged"):
                threats = ", ".join(safe_browsing.get("threat_types", ["MALWARE"]))
                dynamic_recs.append(
                    f"🌐 MALICIOUS LINK ALERT: Google Safe Browsing flagged '{domain}' for security threats ({threats}). Do NOT visit this link or enter passwords."
                )
            elif whois_info.get("is_new_domain"):
                reg_days = whois_info.get("registered_days", "< 90")
                dynamic_recs.append(
                    f"🌐 NEW DOMAIN ADVISORY: The website '{domain}' was registered recently ({reg_days} days ago). Verify company background before applying."
                )

        # 6. Messaging Channels Signal
        matched_channels = risk_factors.get("matched_suspicious_terms")
        extracted_telegrams = (intake_data.get("metadata_extracted") or {}).get("telegram_handles", [])
        if risk_factors.get("has_suspicious_channels") or extracted_telegrams:
            channel_name = extracted_telegrams[0] if extracted_telegrams else (', '.join(matched_channels) if isinstance(matched_channels, list) else "Telegram/WhatsApp")
            dynamic_recs.append(
                f"📵 INFORMAL CONTACT CAUTION: The posting directs applicants to {channel_name}. Professional hiring typically uses company ATS or corporate email domains."
            )

        # 7. Baseline safety recommendations
        if not dynamic_recs:
            dynamic_recs.append("Verify vacancy details through the official company portal before submitting sensitive identity documents.")
            dynamic_recs.append("Never share OTP codes, bank account credentials, or credit card details during a job application process.")

        # Ensure unique items
        seen = set()
        final_recs = []
        for r in dynamic_recs:
            clean_r = r.strip()
            if clean_r and clean_r not in seen:
                seen.add(clean_r)
                final_recs.append(clean_r)

        return final_recs
